# stages:
#   - test
#   - build
  

# test project:
#   stage: test
#   image: node:latest
#   script:
#     - npm install
#     - npm test

# build project:
#   stage: build
#   image: node:latest
#   script: 
#     - npm install
#     - npm run build
#   artifacts:
#     paths:
#       - build/
