image: node:latest

stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - echo "Build phase..."
    - npm install
    - npm run build

job_test:
  stage: test
  script:
    - echo "Cleaning up npm cache..."
    - npm cache clean --force
    - npm install
    - |
      # Exécuter les tests de filtrage des films
      node src/assets/js/ListeFilms.js
      if [ $? -eq 0 ]; then
        echo "Tests de filtrage des films réussis!"
      else
<<<<<<< HEAD
=======
        echo "Échec de l'inscription."
        exit 1
      fi

      # Exécuter les tests de filtrage des films
      node src/assets/js/ListeFilms.js
      if [ $? -eq 0 ]; then
        echo "Tests de filtrage des films réussis!"
      else
>>>>>>> 092cf48f118b524ef8e1cbbe7d116fe85f43103a
        echo "Échec des tests de filtrage des films."
        exit 1
      fi

job_deploy:
  stage: deploy
  script:
    - echo "Deploy phase..."
    # Ajoutez ici les commandes pour déployer votre application
